<?php 
if (!defined('DP_BASE_DIR')) {
	die('You should not access this file directly.');
}
### Copyright (c) 2004, The dotProject Development Team dotproject.net and sf.net/projects/dotproject ###
### All rights reserved. Released under GPL License. For further Information see LICENSE ###

### CONFIGURATION FILE AUTOMATICALLY GENERATED BY THE DOTPROJECT INSTALLER ###
### FOR INFORMATION ON MANUAL CONFIGURATION AND FOR DOCUMENTATION SEE ./includes/config-dist.php ###

$dPconfig['dbtype'] = "mysql";      // ONLY MySQL is supported at present
$dPconfig['dbhost'] = "localhost";
$dPconfig['dbname'] = "c2aps1";  // Change to match your DotProject Database Name
$dPconfig['dbprefix'] = "dotp_";

$dPconfig['dbuser'] = "c2aps1";  // Change to match your MySQL Username
$dPconfig['dbpass'] = "418c6bdc4ba789f8";  // Change to match your MySQL Password
$dPconfig['dbpersist'] = true;
$dPconfig['root_dir'] = $baseDir;
$dPconfig['base_url'] = $baseUrl;

?>